spring:
  application:
    name: emarcket-web-site
  messages:
    basename: messages/messages

server:
  use-forward-headers: true
  context-path: /site
  port: 2000

eureka:
  instance:
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health


security:
  oauth2:
    client:
     clientId: my-trusted-client
     clientSecret:
     accessTokenUri: http://localhost:9090/oauth/token
     userAuthorizationUri: http://localhost:9090/oauth/authorize
     auto-approve-scopes: '.*'
     registered-redirect-uri: http://localhost:9090/login
     clientAuthenticationScheme: form
    resource:
     id: oauth2-resource
     user-info-uri: http://localhost:9090/account/userInfo.json
     preferTokenInfo: false

management:
  security:
    enabled: false

zuul:
  prefix: /api
  sensitiveHeaders:
  ignoredServices: '*'
  ignoreSecurityHeaders: false
  addHostHeader: true
  routes:
    product-catalog-service: /v1/product-catalog-service/**
    account-service: /v1/account-service/**
    purchase-order-service: /v1/purchase-order-service/**