spring:
  application:
    name: purchase-order-service
  data:
    cassandra:
      keyspace-name: purchaseOrderEventKeyspace

external-service:
  base-uri-schema:
    goods-in-product-catalog: http://product-catalog-service/price-list/{priceListId}/goods/{goodsId}
    account: http://account-service/account/{userName}

security:
  oauth2:
    client:
     clientId: my-trusted-client
     clientSecret:
     accessTokenUri: http://localhost:9090/oauth/token
     userAuthorizationUri: http://localhost:9090/oauth/authorize
     auto-approve-scopes: '.*'
     registered-redirect-uri: http://localhost:9090/login
     clientAuthenticationScheme: form
    resource:
     id: oauth2-resource
     user-info-uri: http://localhost:9090/account/userInfo.json