security:
   oauth2:
     client:
       clientId: my-trusted-client
       clientSecret:
       accessTokenUri: http://localhost:5050/v1/account-service/oauth/access_token
       userAuthorizationUri: http://localhost:5050/v1/account-service/oauth/authorize
       clientAuthenticationScheme: form
     resource:
       userInfoUri: http://localhost:5050/v1/account-service/account/userInfo
       preferTokenInfo: false

spring:
  data:
    cassandra:
      keyspace-name: productCatalogEventKeyspace
      schema-action: create_if_not_exists
    mongodb:
      database: product-catalog

server:
  use-forward-headers: true